### ISSUE TITLE
Can not apply on the dicom images

### ISSUE THREAD

**Issue by dgvai** [mbalatsko/opencv-rolling-ball#2]
The execution never stops when I pass a dicom image pixel array to its input. Can anyone tell the correct procedure to that?

My code:
```
import cv2
from cv2_rolling_ball import subtract_background_rolling_ball
import pydicom as dicom
...

dcm_img = dicom.dcmread("./left.dcm")

img, bg = subtract_background_rolling_ball(dcm_img.pixel_array, radius=50, light_background=False, use_paraboloid=True)

cv2.imshow('Original Image', img)
cv2.waitKey(0)

```

**Comment by JakubNovak** [comment]
Hi @dgvai ,

what is the exact error output message of your code? Also, consider followings:

*  Is your dicom data colored or monochrome?
* What is the `.shape` of your data?
* How big is your dicom data?
* Are you even able to display the dicom data?

Thanks for sharing these information with us.

**Comment by dgvai** [comment]
hello @JakubNovak 
I am seeing any error, because the execution never completes.

- Yes, my image is grayscale
-  The .dcm file pretty huge, 40mb in size

**Comment by JakubNovak** [comment]
Does it happen only on that file or on any dicom data file?
Can you share your data?

**Comment by dgvai** [comment]
Yes, here is one dcm file, try if you can apply rolling ball bg subtractor 

https://drive.google.com/file/d/1sJsShw1GA0Dgi2fJ5o65_RCyd-5n5rpb/view?usp=sharing

**Comment by JakubNovak** [comment]
Well I tried it on your data and it finished. It just run exactly for 2,5 hours...
You can see the result [here](https://deepnote.com/@jakub-novk-d648/Dicom-Snowball-test-2Sc91j56TbOkam0EjBL2gg).

I'm closing the issue as solved.
